# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(863, 545)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        Window.setFont(font)
        Window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Analyzer = QtWidgets.QPushButton(Window)
        self.Analyzer.setGeometry(QtCore.QRect(0, 0, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Analyzer.setFont(font)
        self.Analyzer.setStyleSheet("\n"
"border: 3px solid ;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color : None;\n"
"    min-width: 80px; \n"
"")
        self.Analyzer.setObjectName("Analyzer")
        self.Traider = QtWidgets.QPushButton(Window)
        self.Traider.setGeometry(QtCore.QRect(100, 0, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Traider.setFont(font)
        self.Traider.setStyleSheet("border: 3px solid ;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color : None;\n"
"    min-width: 80px; ")
        self.Traider.setObjectName("Traider")
        self.mainframe = QtWidgets.QFrame(Window)
        self.mainframe.setGeometry(QtCore.QRect(0, 0, 1001, 41))
        self.mainframe.setStyleSheet("\n"
"border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);")
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.frame_2 = QtWidgets.QFrame(Window)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 1001, 51))
        self.frame_2.setStyleSheet("\n"
"border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textStart = QtWidgets.QTextBrowser(self.frame_2)
        self.textStart.setGeometry(QtCore.QRect(0, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.textStart.setFont(font)
        self.textStart.setAcceptDrops(False)
        self.textStart.setStyleSheet("background-color: None;\n"
"border-color : None;\n"
"")
        self.textStart.setObjectName("textStart")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 171, 51))
        self.frame.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolButton_Start = QtWidgets.QToolButton(self.frame)
        self.toolButton_Start.setEnabled(True)
        self.toolButton_Start.setGeometry(QtCore.QRect(120, 19, 31, 20))
        self.toolButton_Start.setAutoRaise(False)
        self.toolButton_Start.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_Start.setObjectName("toolButton_Start")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(170, 0, 161, 51))
        self.frame_3.setStyleSheet("\n"
"border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textEnd = QtWidgets.QTextBrowser(self.frame_3)
        self.textEnd.setGeometry(QtCore.QRect(0, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.textEnd.setFont(font)
        self.textEnd.setAcceptDrops(False)
        self.textEnd.setStyleSheet("background-color: None;\n"
"border-color : None;\n"
"")
        self.textEnd.setObjectName("textEnd")
        self.toolButton_End = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_End.setEnabled(True)
        self.toolButton_End.setGeometry(QtCore.QRect(100, 18, 31, 21))
        self.toolButton_End.setAutoRaise(False)
        self.toolButton_End.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_End.setObjectName("toolButton_End")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setGeometry(QtCore.QRect(330, 0, 111, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.toolButton_Coin = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_Coin.setEnabled(True)
        self.toolButton_Coin.setGeometry(QtCore.QRect(390, 20, 31, 21))
        self.toolButton_Coin.setAutoRaise(False)
        self.toolButton_Coin.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_Coin.setObjectName("toolButton_Coin")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 863, 51))
        self.frame_4.setStyleSheet("\n"
"border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.textStart_2 = QtWidgets.QTextBrowser(self.frame_4)
        self.textStart_2.setGeometry(QtCore.QRect(0, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.textStart_2.setFont(font)
        self.textStart_2.setAcceptDrops(False)
        self.textStart_2.setStyleSheet("background-color: None;\n"
"border-color : None;\n"
"")
        self.textStart_2.setObjectName("textStart_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 171, 51))
        self.frame_5.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.toolButton_Start_2 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_Start_2.setEnabled(True)
        self.toolButton_Start_2.setGeometry(QtCore.QRect(120, 19, 31, 20))
        self.toolButton_Start_2.setAutoRaise(False)
        self.toolButton_Start_2.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_Start_2.setObjectName("toolButton_Start_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(170, 0, 161, 51))
        self.frame_6.setStyleSheet("\n"
"border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.textEnd_2 = QtWidgets.QTextBrowser(self.frame_6)
        self.textEnd_2.setGeometry(QtCore.QRect(0, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.textEnd_2.setFont(font)
        self.textEnd_2.setAcceptDrops(False)
        self.textEnd_2.setStyleSheet("background-color: None;\n"
"border-color : None;\n"
"")
        self.textEnd_2.setObjectName("textEnd_2")
        self.toolButton_End_2 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_End_2.setEnabled(True)
        self.toolButton_End_2.setGeometry(QtCore.QRect(100, 18, 31, 21))
        self.toolButton_End_2.setAutoRaise(False)
        self.toolButton_End_2.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_End_2.setObjectName("toolButton_End_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_2.setGeometry(QtCore.QRect(330, 0, 111, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.toolButton_Coin_2 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_Coin_2.setEnabled(True)
        self.toolButton_Coin_2.setGeometry(QtCore.QRect(390, 20, 31, 21))
        self.toolButton_Coin_2.setAutoRaise(False)
        self.toolButton_Coin_2.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_Coin_2.setObjectName("toolButton_Coin_2")
        self.Submit = QtWidgets.QPushButton(self.frame_4)
        self.Submit.setGeometry(QtCore.QRect(760, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Submit.setFont(font)
        self.Submit.setStyleSheet("\n"
"border: 3px solid ;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color : None;\n"
"    min-width: 80px; \n"
"")
        self.Submit.setObjectName("Submit")
        self.frame_4.raise_()
        self.textStart.raise_()
        self.frame.raise_()
        self.frame_3.raise_()
        self.textBrowser.raise_()
        self.toolButton_Coin.raise_()
        self.Startdate = QtWidgets.QDateEdit(Window)
        self.Startdate.setEnabled(True)
        self.Startdate.setGeometry(QtCore.QRect(110, 90, 141, 22))
        self.Startdate.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"")
        self.Startdate.setMinimumDate(QtCore.QDate(2015, 9, 14))
        self.Startdate.setCalendarPopup(False)
        self.Startdate.setCurrentSectionIndex(0)
        self.Startdate.setObjectName("Startdate")
        self.Enddate = QtWidgets.QDateEdit(Window)
        self.Enddate.setEnabled(True)
        self.Enddate.setGeometry(QtCore.QRect(260, 90, 141, 22))
        self.Enddate.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"")
        self.Enddate.setMinimumDate(QtCore.QDate(2015, 9, 14))
        self.Enddate.setCalendarPopup(False)
        self.Enddate.setCurrentSectionIndex(0)
        self.Enddate.setObjectName("Enddate")
        self.listWidget = QtWidgets.QListWidget(Window)
        self.listWidget.setGeometry(QtCore.QRect(400, 90, 151, 61))
        self.listWidget.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        item.setFont(font)
        self.listWidget.addItem(item)
        self.frame_7 = QtWidgets.QFrame(Window)
        self.frame_7.setGeometry(QtCore.QRect(0, 90, 901, 221))
        self.frame_7.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setGeometry(QtCore.QRect(-50, 0, 921, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("CryptZ/fig3.png"))
        self.label.setObjectName("label")
        self.frame_8 = QtWidgets.QFrame(Window)
        self.frame_8.setGeometry(QtCore.QRect(0, 310, 331, 41))
        self.frame_8.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(150, 0, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_9 = QtWidgets.QFrame(Window)
        self.frame_9.setGeometry(QtCore.QRect(0, 510, 331, 41))
        self.frame_9.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.Tabledate = QtWidgets.QDateEdit(self.frame_9)
        self.Tabledate.setEnabled(True)
        self.Tabledate.setGeometry(QtCore.QRect(180, 0, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.Tabledate.setFont(font)
        self.Tabledate.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"")
        self.Tabledate.setMinimumDate(QtCore.QDate(2015, 10, 29))
        self.Tabledate.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.Tabledate.setCalendarPopup(False)
        self.Tabledate.setCurrentSectionIndex(1)
        self.Tabledate.setObjectName("Tabledate")
        self.toolButton_tabledate = QtWidgets.QToolButton(self.frame_9)
        self.toolButton_tabledate.setEnabled(True)
        self.toolButton_tabledate.setGeometry(QtCore.QRect(150, 10, 31, 20))
        self.toolButton_tabledate.setAutoRaise(False)
        self.toolButton_tabledate.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_tabledate.setObjectName("toolButton_tabledate")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-width: 0px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.label_4.setObjectName("label_4")
        self.scrollArea = QtWidgets.QScrollArea(Window)
        self.scrollArea.setGeometry(QtCore.QRect(0, 350, 331, 161))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: rgb(255, 255, 255)")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 312, 818))
        self.scrollAreaWidgetContents.setStyleSheet("border-width: 0px;\n"
"\n"
"background-color: None")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_Day_23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_23.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_23.setFont(font)
        self.lineEdit_Day_23.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_23.setText("")
        self.lineEdit_Day_23.setReadOnly(True)
        self.lineEdit_Day_23.setObjectName("lineEdit_Day_23")
        self.gridLayout.addWidget(self.lineEdit_Day_23, 31, 0, 1, 1)
        self.lineEdit_Day_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_2.setFont(font)
        self.lineEdit_Day_2.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_2.setReadOnly(True)
        self.lineEdit_Day_2.setObjectName("lineEdit_Day_2")
        self.gridLayout.addWidget(self.lineEdit_Day_2, 1, 0, 1, 1)
        self.lineEdit_Day_26 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_26.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_26.setFont(font)
        self.lineEdit_Day_26.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_26.setText("")
        self.lineEdit_Day_26.setReadOnly(True)
        self.lineEdit_Day_26.setObjectName("lineEdit_Day_26")
        self.gridLayout.addWidget(self.lineEdit_Day_26, 36, 0, 1, 1)
        self.lineEdit_Value_30 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_30.setFont(font)
        self.lineEdit_Value_30.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_30.setReadOnly(True)
        self.lineEdit_Value_30.setObjectName("lineEdit_Value_30")
        self.gridLayout.addWidget(self.lineEdit_Value_30, 42, 1, 1, 1)
        self.lineEdit_Day_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_17.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_17.setFont(font)
        self.lineEdit_Day_17.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_17.setText("")
        self.lineEdit_Day_17.setReadOnly(True)
        self.lineEdit_Day_17.setObjectName("lineEdit_Day_17")
        self.gridLayout.addWidget(self.lineEdit_Day_17, 23, 0, 1, 1)
        self.lineEdit_Day_28 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_28.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_28.setFont(font)
        self.lineEdit_Day_28.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_28.setText("")
        self.lineEdit_Day_28.setReadOnly(True)
        self.lineEdit_Day_28.setObjectName("lineEdit_Day_28")
        self.gridLayout.addWidget(self.lineEdit_Day_28, 39, 0, 1, 1)
        self.lineEdit_Value_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_2.setFont(font)
        self.lineEdit_Value_2.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_2.setReadOnly(True)
        self.lineEdit_Value_2.setObjectName("lineEdit_Value_2")
        self.gridLayout.addWidget(self.lineEdit_Value_2, 1, 1, 1, 1)
        self.lineEdit_Value_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_4.setFont(font)
        self.lineEdit_Value_4.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_4.setReadOnly(True)
        self.lineEdit_Value_4.setObjectName("lineEdit_Value_4")
        self.gridLayout.addWidget(self.lineEdit_Value_4, 3, 1, 1, 1)
        self.lineEdit_Value_22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_22.setFont(font)
        self.lineEdit_Value_22.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_22.setReadOnly(True)
        self.lineEdit_Value_22.setObjectName("lineEdit_Value_22")
        self.gridLayout.addWidget(self.lineEdit_Value_22, 30, 1, 1, 1)
        self.lineEdit_Day_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_9.setFont(font)
        self.lineEdit_Day_9.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_9.setReadOnly(True)
        self.lineEdit_Day_9.setObjectName("lineEdit_Day_9")
        self.gridLayout.addWidget(self.lineEdit_Day_9, 11, 0, 1, 1)
        self.lineEdit_Day_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_20.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_20.setFont(font)
        self.lineEdit_Day_20.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_20.setText("")
        self.lineEdit_Day_20.setReadOnly(True)
        self.lineEdit_Day_20.setObjectName("lineEdit_Day_20")
        self.gridLayout.addWidget(self.lineEdit_Day_20, 27, 0, 1, 1)
        self.lineEdit_Day_25 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_25.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_25.setFont(font)
        self.lineEdit_Day_25.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_25.setText("")
        self.lineEdit_Day_25.setReadOnly(True)
        self.lineEdit_Day_25.setObjectName("lineEdit_Day_25")
        self.gridLayout.addWidget(self.lineEdit_Day_25, 34, 0, 1, 1)
        self.lineEdit_Day_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_19.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_19.setFont(font)
        self.lineEdit_Day_19.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_19.setText("")
        self.lineEdit_Day_19.setReadOnly(True)
        self.lineEdit_Day_19.setObjectName("lineEdit_Day_19")
        self.gridLayout.addWidget(self.lineEdit_Day_19, 25, 0, 1, 1)
        self.lineEdit_Day_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_16.setFont(font)
        self.lineEdit_Day_16.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_16.setReadOnly(True)
        self.lineEdit_Day_16.setObjectName("lineEdit_Day_16")
        self.gridLayout.addWidget(self.lineEdit_Day_16, 21, 0, 1, 1)
        self.lineEdit_Day_24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_24.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_24.setFont(font)
        self.lineEdit_Day_24.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_24.setText("")
        self.lineEdit_Day_24.setReadOnly(True)
        self.lineEdit_Day_24.setObjectName("lineEdit_Day_24")
        self.gridLayout.addWidget(self.lineEdit_Day_24, 33, 0, 1, 1)
        self.lineEdit_Value_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_18.setFont(font)
        self.lineEdit_Value_18.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_18.setReadOnly(True)
        self.lineEdit_Value_18.setObjectName("lineEdit_Value_18")
        self.gridLayout.addWidget(self.lineEdit_Value_18, 24, 1, 1, 1)
        self.lineEdit_Value_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_12.setFont(font)
        self.lineEdit_Value_12.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_12.setReadOnly(True)
        self.lineEdit_Value_12.setObjectName("lineEdit_Value_12")
        self.gridLayout.addWidget(self.lineEdit_Value_12, 16, 1, 1, 1)
        self.lineEdit_Day_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_8.setFont(font)
        self.lineEdit_Day_8.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_8.setReadOnly(True)
        self.lineEdit_Day_8.setObjectName("lineEdit_Day_8")
        self.gridLayout.addWidget(self.lineEdit_Day_8, 8, 0, 1, 1)
        self.lineEdit_Day_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_11.setFont(font)
        self.lineEdit_Day_11.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_11.setReadOnly(True)
        self.lineEdit_Day_11.setObjectName("lineEdit_Day_11")
        self.gridLayout.addWidget(self.lineEdit_Day_11, 13, 0, 1, 1)
        self.lineEdit_Value_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_11.setFont(font)
        self.lineEdit_Value_11.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_11.setReadOnly(True)
        self.lineEdit_Value_11.setObjectName("lineEdit_Value_11")
        self.gridLayout.addWidget(self.lineEdit_Value_11, 13, 1, 1, 1)
        self.lineEdit_Day_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_13.setFont(font)
        self.lineEdit_Day_13.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_13.setReadOnly(True)
        self.lineEdit_Day_13.setObjectName("lineEdit_Day_13")
        self.gridLayout.addWidget(self.lineEdit_Day_13, 17, 0, 1, 1)
        self.lineEdit_Day_29 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_29.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_29.setFont(font)
        self.lineEdit_Day_29.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_29.setText("")
        self.lineEdit_Day_29.setReadOnly(True)
        self.lineEdit_Day_29.setObjectName("lineEdit_Day_29")
        self.gridLayout.addWidget(self.lineEdit_Day_29, 41, 0, 1, 1)
        self.lineEdit_Day_27 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_27.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_27.setFont(font)
        self.lineEdit_Day_27.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_27.setText("")
        self.lineEdit_Day_27.setReadOnly(True)
        self.lineEdit_Day_27.setObjectName("lineEdit_Day_27")
        self.gridLayout.addWidget(self.lineEdit_Day_27, 37, 0, 1, 1)
        self.lineEdit_Value = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value.setFont(font)
        self.lineEdit_Value.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value.setReadOnly(True)
        self.lineEdit_Value.setObjectName("lineEdit_Value")
        self.gridLayout.addWidget(self.lineEdit_Value, 0, 1, 1, 1)
        self.lineEdit_Value_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_5.setFont(font)
        self.lineEdit_Value_5.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_5.setReadOnly(True)
        self.lineEdit_Value_5.setObjectName("lineEdit_Value_5")
        self.gridLayout.addWidget(self.lineEdit_Value_5, 4, 1, 1, 1)
        self.lineEdit_Day_30 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_30.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_30.setFont(font)
        self.lineEdit_Day_30.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_30.setText("")
        self.lineEdit_Day_30.setReadOnly(True)
        self.lineEdit_Day_30.setObjectName("lineEdit_Day_30")
        self.gridLayout.addWidget(self.lineEdit_Day_30, 42, 0, 1, 1)
        self.lineEdit_Value_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_3.setFont(font)
        self.lineEdit_Value_3.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_3.setReadOnly(True)
        self.lineEdit_Value_3.setObjectName("lineEdit_Value_3")
        self.gridLayout.addWidget(self.lineEdit_Value_3, 2, 1, 1, 1)
        self.lineEdit_Value_27 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_27.setFont(font)
        self.lineEdit_Value_27.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_27.setReadOnly(True)
        self.lineEdit_Value_27.setObjectName("lineEdit_Value_27")
        self.gridLayout.addWidget(self.lineEdit_Value_27, 37, 1, 1, 1)
        self.lineEdit_Day_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_10.setFont(font)
        self.lineEdit_Day_10.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_10.setReadOnly(True)
        self.lineEdit_Day_10.setObjectName("lineEdit_Day_10")
        self.gridLayout.addWidget(self.lineEdit_Day_10, 12, 0, 1, 1)
        self.lineEdit_Value_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_10.setFont(font)
        self.lineEdit_Value_10.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_10.setReadOnly(True)
        self.lineEdit_Value_10.setObjectName("lineEdit_Value_10")
        self.gridLayout.addWidget(self.lineEdit_Value_10, 12, 1, 1, 1)
        self.lineEdit_Value_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_7.setFont(font)
        self.lineEdit_Value_7.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_7.setReadOnly(True)
        self.lineEdit_Value_7.setObjectName("lineEdit_Value_7")
        self.gridLayout.addWidget(self.lineEdit_Value_7, 7, 1, 1, 1)
        self.lineEdit_Value_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_13.setFont(font)
        self.lineEdit_Value_13.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_13.setReadOnly(True)
        self.lineEdit_Value_13.setObjectName("lineEdit_Value_13")
        self.gridLayout.addWidget(self.lineEdit_Value_13, 17, 1, 1, 1)
        self.lineEdit_Value_28 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_28.setFont(font)
        self.lineEdit_Value_28.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_28.setReadOnly(True)
        self.lineEdit_Value_28.setObjectName("lineEdit_Value_28")
        self.gridLayout.addWidget(self.lineEdit_Value_28, 39, 1, 1, 1)
        self.lineEdit_Value_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_16.setFont(font)
        self.lineEdit_Value_16.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_16.setReadOnly(True)
        self.lineEdit_Value_16.setObjectName("lineEdit_Value_16")
        self.gridLayout.addWidget(self.lineEdit_Value_16, 21, 1, 1, 1)
        self.lineEdit_Day_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_18.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_18.setFont(font)
        self.lineEdit_Day_18.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_18.setText("")
        self.lineEdit_Day_18.setReadOnly(True)
        self.lineEdit_Day_18.setObjectName("lineEdit_Day_18")
        self.gridLayout.addWidget(self.lineEdit_Day_18, 24, 0, 1, 1)
        self.lineEdit_Value_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_17.setFont(font)
        self.lineEdit_Value_17.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_17.setReadOnly(True)
        self.lineEdit_Value_17.setObjectName("lineEdit_Value_17")
        self.gridLayout.addWidget(self.lineEdit_Value_17, 23, 1, 1, 1)
        self.lineEdit_Day_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_5.setFont(font)
        self.lineEdit_Day_5.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_5.setReadOnly(True)
        self.lineEdit_Day_5.setObjectName("lineEdit_Day_5")
        self.gridLayout.addWidget(self.lineEdit_Day_5, 4, 0, 1, 1)
        self.lineEdit_Value_29 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_29.setFont(font)
        self.lineEdit_Value_29.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_29.setReadOnly(True)
        self.lineEdit_Value_29.setObjectName("lineEdit_Value_29")
        self.gridLayout.addWidget(self.lineEdit_Value_29, 41, 1, 1, 1)
        self.lineEdit_Day_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_7.setFont(font)
        self.lineEdit_Day_7.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_7.setReadOnly(True)
        self.lineEdit_Day_7.setObjectName("lineEdit_Day_7")
        self.gridLayout.addWidget(self.lineEdit_Day_7, 7, 0, 1, 1)
        self.lineEdit_Day = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day.setFont(font)
        self.lineEdit_Day.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day.setText("")
        self.lineEdit_Day.setReadOnly(True)
        self.lineEdit_Day.setObjectName("lineEdit_Day")
        self.gridLayout.addWidget(self.lineEdit_Day, 0, 0, 1, 1)
        self.lineEdit_Value_26 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_26.setFont(font)
        self.lineEdit_Value_26.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_26.setReadOnly(True)
        self.lineEdit_Value_26.setObjectName("lineEdit_Value_26")
        self.gridLayout.addWidget(self.lineEdit_Value_26, 36, 1, 1, 1)
        self.lineEdit_Value_24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_24.setFont(font)
        self.lineEdit_Value_24.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_24.setReadOnly(True)
        self.lineEdit_Value_24.setObjectName("lineEdit_Value_24")
        self.gridLayout.addWidget(self.lineEdit_Value_24, 33, 1, 1, 1)
        self.lineEdit_Day_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_14.setFont(font)
        self.lineEdit_Day_14.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_14.setReadOnly(True)
        self.lineEdit_Day_14.setObjectName("lineEdit_Day_14")
        self.gridLayout.addWidget(self.lineEdit_Day_14, 18, 0, 1, 1)
        self.lineEdit_Value_23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_23.setFont(font)
        self.lineEdit_Value_23.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_23.setReadOnly(True)
        self.lineEdit_Value_23.setObjectName("lineEdit_Value_23")
        self.gridLayout.addWidget(self.lineEdit_Value_23, 31, 1, 1, 1)
        self.lineEdit_Value_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_19.setFont(font)
        self.lineEdit_Value_19.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_19.setReadOnly(True)
        self.lineEdit_Value_19.setObjectName("lineEdit_Value_19")
        self.gridLayout.addWidget(self.lineEdit_Value_19, 25, 1, 1, 1)
        self.lineEdit_Value_31 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_31.setFont(font)
        self.lineEdit_Value_31.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_31.setReadOnly(True)
        self.lineEdit_Value_31.setObjectName("lineEdit_Value_31")
        self.gridLayout.addWidget(self.lineEdit_Value_31, 43, 1, 1, 1)
        self.lineEdit_Day_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_12.setFont(font)
        self.lineEdit_Day_12.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_12.setReadOnly(True)
        self.lineEdit_Day_12.setObjectName("lineEdit_Day_12")
        self.gridLayout.addWidget(self.lineEdit_Day_12, 16, 0, 1, 1)
        self.lineEdit_Value_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_14.setFont(font)
        self.lineEdit_Value_14.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_14.setReadOnly(True)
        self.lineEdit_Value_14.setObjectName("lineEdit_Value_14")
        self.gridLayout.addWidget(self.lineEdit_Value_14, 18, 1, 1, 1)
        self.lineEdit_Day_31 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_31.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_31.setFont(font)
        self.lineEdit_Day_31.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_31.setText("")
        self.lineEdit_Day_31.setReadOnly(True)
        self.lineEdit_Day_31.setObjectName("lineEdit_Day_31")
        self.gridLayout.addWidget(self.lineEdit_Day_31, 43, 0, 1, 1)
        self.lineEdit_Value_25 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_25.setFont(font)
        self.lineEdit_Value_25.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_25.setReadOnly(True)
        self.lineEdit_Value_25.setObjectName("lineEdit_Value_25")
        self.gridLayout.addWidget(self.lineEdit_Value_25, 34, 1, 1, 1)
        self.lineEdit_Day_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_15.setFont(font)
        self.lineEdit_Day_15.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_15.setReadOnly(True)
        self.lineEdit_Day_15.setObjectName("lineEdit_Day_15")
        self.gridLayout.addWidget(self.lineEdit_Day_15, 20, 0, 1, 1)
        self.lineEdit_Day_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_3.setFont(font)
        self.lineEdit_Day_3.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_3.setReadOnly(True)
        self.lineEdit_Day_3.setObjectName("lineEdit_Day_3")
        self.gridLayout.addWidget(self.lineEdit_Day_3, 2, 0, 1, 1)
        self.lineEdit_Value_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_15.setFont(font)
        self.lineEdit_Value_15.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_15.setReadOnly(True)
        self.lineEdit_Value_15.setObjectName("lineEdit_Value_15")
        self.gridLayout.addWidget(self.lineEdit_Value_15, 20, 1, 1, 1)
        self.lineEdit_Day_22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_22.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_22.setFont(font)
        self.lineEdit_Day_22.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_22.setText("")
        self.lineEdit_Day_22.setReadOnly(True)
        self.lineEdit_Day_22.setObjectName("lineEdit_Day_22")
        self.gridLayout.addWidget(self.lineEdit_Day_22, 30, 0, 1, 1)
        self.lineEdit_Day_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_4.setFont(font)
        self.lineEdit_Day_4.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_4.setReadOnly(True)
        self.lineEdit_Day_4.setObjectName("lineEdit_Day_4")
        self.gridLayout.addWidget(self.lineEdit_Day_4, 3, 0, 1, 1)
        self.lineEdit_Value_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_9.setFont(font)
        self.lineEdit_Value_9.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_9.setReadOnly(True)
        self.lineEdit_Value_9.setObjectName("lineEdit_Value_9")
        self.gridLayout.addWidget(self.lineEdit_Value_9, 11, 1, 1, 1)
        self.lineEdit_Value_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_20.setFont(font)
        self.lineEdit_Value_20.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_20.setReadOnly(True)
        self.lineEdit_Value_20.setObjectName("lineEdit_Value_20")
        self.gridLayout.addWidget(self.lineEdit_Value_20, 27, 1, 1, 1)
        self.lineEdit_Value_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_8.setFont(font)
        self.lineEdit_Value_8.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_8.setReadOnly(True)
        self.lineEdit_Value_8.setObjectName("lineEdit_Value_8")
        self.gridLayout.addWidget(self.lineEdit_Value_8, 8, 1, 1, 1)
        self.lineEdit_Value_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_21.setFont(font)
        self.lineEdit_Value_21.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_21.setReadOnly(True)
        self.lineEdit_Value_21.setObjectName("lineEdit_Value_21")
        self.gridLayout.addWidget(self.lineEdit_Value_21, 28, 1, 1, 1)
        self.lineEdit_Day_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Day_21.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_21.setFont(font)
        self.lineEdit_Day_21.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_21.setText("")
        self.lineEdit_Day_21.setReadOnly(True)
        self.lineEdit_Day_21.setObjectName("lineEdit_Day_21")
        self.gridLayout.addWidget(self.lineEdit_Day_21, 28, 0, 1, 1)
        self.lineEdit_Value_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Value_6.setFont(font)
        self.lineEdit_Value_6.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Value_6.setReadOnly(True)
        self.lineEdit_Value_6.setObjectName("lineEdit_Value_6")
        self.gridLayout.addWidget(self.lineEdit_Value_6, 5, 1, 1, 1)
        self.lineEdit_Day_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.lineEdit_Day_6.setFont(font)
        self.lineEdit_Day_6.setStyleSheet("border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(211, 211, 211);\n"
"background-color: None")
        self.lineEdit_Day_6.setReadOnly(True)
        self.lineEdit_Day_6.setObjectName("lineEdit_Day_6")
        self.gridLayout.addWidget(self.lineEdit_Day_6, 5, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.frame_9.raise_()
        self.frame_7.raise_()
        self.mainframe.raise_()
        self.Analyzer.raise_()
        self.Traider.raise_()
        self.Startdate.raise_()
        self.frame_2.raise_()
        self.Enddate.raise_()
        self.listWidget.raise_()
        self.frame_8.raise_()

        self.retranslateUi(Window)
        self.toolButton_Start.clicked.connect(self.Startdate.show)
        self.Startdate.editingFinished.connect(self.Startdate.hide)
        self.toolButton_End.clicked.connect(self.Enddate.show)
        self.Enddate.editingFinished.connect(self.Enddate.hide)
        self.listWidget.itemClicked['QListWidgetItem*'].connect(self.listWidget.hide)
        self.toolButton_Coin.clicked.connect(self.listWidget.show)
        self.Tabledate.editingFinished.connect(self.Tabledate.hide)
        self.toolButton_tabledate.clicked.connect(self.Tabledate.show)
        self.Submit.clicked.connect(self.label.show)
        self.Analyzer.clicked.connect(self.label.hide)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Window"))
        self.Analyzer.setText(_translate("Window", "Analyzer"))
        self.Traider.setText(_translate("Window", "Traider"))
        self.textStart.setHtml(_translate("Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Start Date</p></body></html>"))
        self.toolButton_Start.setText(_translate("Window", "..."))
        self.textEnd.setHtml(_translate("Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">End Date</p></body></html>"))
        self.toolButton_End.setText(_translate("Window", "..."))
        self.textBrowser.setHtml(_translate("Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Console\'; font-size:12pt;\">Coin</span></p></body></html>"))
        self.toolButton_Coin.setText(_translate("Window", "..."))
        self.textStart_2.setHtml(_translate("Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Start Date</p></body></html>"))
        self.toolButton_Start_2.setText(_translate("Window", "..."))
        self.textEnd_2.setHtml(_translate("Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">End Date</p></body></html>"))
        self.toolButton_End_2.setText(_translate("Window", "..."))
        self.textBrowser_2.setHtml(_translate("Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Console\'; font-size:12pt;\">Coin</span></p></body></html>"))
        self.toolButton_Coin_2.setText(_translate("Window", "..."))
        self.Submit.setText(_translate("Window", "Submit!"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Window", "BitCoin"))
        item = self.listWidget.item(1)
        item.setText(_translate("Window", "SMTH Else"))
        item = self.listWidget.item(2)
        item.setText(_translate("Window", "Ethirium"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Window", "Date"))
        self.label_3.setText(_translate("Window", "Price in USD"))
        self.toolButton_tabledate.setText(_translate("Window", "..."))
        self.label_4.setText(_translate("Window", "Choose month"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QWidget()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
